---
# tasks file for duckdb

#
# Install DuckDB  - https://duckdb.org/
#

- name: Get regular user
  ansible.builtin.set_fact:
    remote_regular_user: "{{ ansible_env.SUDO_USER or ansible_user_id }}"

- name: Check if duckdb is already installed
  ansible.builtin.command: "~{{ remote_regular_user }}/.local/bin/duckdb -version"
  register: duckdb_ver
  ignore_errors: true
  changed_when: false

# - debug:
#     var: duckdb_ver

- name: Get duckdb binary package
  ansible.builtin.unarchive:
    src: "{{ duckdb_download_url }}"
    dest: "~{{ remote_regular_user }}/.local/bin/"
    remote_src: true
    mode: '0755'
    owner: "{{ remote_regular_user }}"
    group: "{{ remote_regular_user }}"
  when: duckdb_ver.failed
