---
# tasks file for packages

#
# Manage available packages on the workstation
#

- name: DNF increase simultaneous package downloads
  ansible.builtin.lineinfile:
    path: /etc/dnf/dnf.conf
    line: max_parallel_downloads=10

- name: Upgrade all packages
  ansible.builtin.dnf:
    name: "*"
    state: latest
    update_cache: true
    update_only: true

- name: Installing additional packages
  ansible.builtin.dnf:
    name: "{{ packages_extra_packages }}"

- name: Install Ansible-lint
  ansible.builtin.pip:
    name: Ansible-lint
  args:
    state: present

- name: Removing a few workstation packages
  ansible.builtin.dnf:
    name: "{{ packages_remove_packages }}"
    state: absent
  when: delete_software
