---
# tasks file for tweaks

# https://extensions.gnome.org/
- name: Import requirements for Gnome Shell extensions
  ansible.builtin.import_tasks: tasks/requirements.yml

- name: Install a few Gnome Shell Extensions
  ansible.builtin.dnf:
    name: "{{ tweaks_extension_packages }}"
    state: present
  when: install_gnome_extensions

# Tweking the Gnome Desktop
- name: Apply some tweaks to the Shell
  become: false
  block:
    - name: Apply Adwaita Dark theme
      community.general.dconf:
        key: /org/gnome/desktop/interface/gtk-theme
        value: "'Adwaita-dark'"

    - name: Enable Night Light
      community.general.dconf:
        key: /org/gnome/settings-daemon/plugins/color/night-light-enabled
        value: 'true'

    # - name: Set Attach Modal Dialogs
    #   community.general.dconf:
    #     key: /org/gnome/mutter/attach-modal-dialogs
    #     value: 'false'

    # - name: Terminal Custom Shortcut
    #   community.general.dconf:
    #     key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0
    #     binding: '<Super>Return'
    #     command: 'gnome-terminal'
    #     name: 'terminal'
